export enum Status {
  ACTIVO = 'ACTIVO',
  INACTIVO = 'INACTIVO',
  ASISTIO = 'ASISTIO',
  AUSENTE = 'AUSENTE',
  NO_MATRICULADO = 'NO MATRICULADO',
}

export enum TypeUsers {
  ADMIN = 'ADMIN',
  PARENT = 'PARENT',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
}
